### ISSUE TITLE
Update Git for Windows installation instructions

### ISSUE THREAD

**Issue by rgaiacs** [dgasmith/2015-08-24-stanford#2]
This is a kindly remember to merge https://github.com/swcarpentry/workshop-template/pull/235 that you can do with

```
$ git remote add upstream https://github.com/swcarpentry/workshop-template.git
$ git fetch upstream
$ git merge upstream/gh-pages
$ git push origin gh-pages
```

**Comment by dgasmith** [comment]
Whoops, did this awhile ago and forgot to close this. Thanks for the hint.
